/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResumoRouteImport } from './routes/resumo'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RendaRouteImport } from './routes/renda'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as RecuperarSenhaRouteImport } from './routes/recuperar-senha'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as OrcamentoRouteImport } from './routes/orcamento'
import { Route as MeuPlanoRouteImport } from './routes/meu-plano'
import { Route as MetasRouteImport } from './routes/metas'
import { Route as ManualRouteImport } from './routes/manual'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GuardadoRouteImport } from './routes/guardado'
import { Route as GastosRouteImport } from './routes/gastos'
import { Route as ContasAPagarRouteImport } from './routes/contas-a-pagar'
import { Route as ContaRouteImport } from './routes/conta'
import { Route as ConfirmarRouteImport } from './routes/confirmar'
import { Route as CategoriasRouteImport } from './routes/categorias'
import { Route as CartoesRouteImport } from './routes/cartoes'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as AdicionarRouteImport } from './routes/adicionar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiOcrGastoRouteImport } from './routes/api/ocr-gasto'
import { Route as ApiImportFaturaPdfRouteImport } from './routes/api/import-fatura-pdf'
import { Route as ApiImportFaturaImagemRouteImport } from './routes/api/import-fatura-imagem'
import { Route as ApiImportExtratoRouteImport } from './routes/api/import-extrato'
import { Route as ApiImportContaPdfRouteImport } from './routes/api/import-conta-pdf'
import { Route as ApiImportContaRouteImport } from './routes/api/import-conta'

const ResumoRoute = ResumoRouteImport.update({
  id: '/resumo',
  path: '/resumo',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RendaRoute = RendaRouteImport.update({
  id: '/renda',
  path: '/renda',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarSenhaRoute = RecuperarSenhaRouteImport.update({
  id: '/recuperar-senha',
  path: '/recuperar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const OrcamentoRoute = OrcamentoRouteImport.update({
  id: '/orcamento',
  path: '/orcamento',
  getParentRoute: () => rootRouteImport,
} as any)
const MeuPlanoRoute = MeuPlanoRouteImport.update({
  id: '/meu-plano',
  path: '/meu-plano',
  getParentRoute: () => rootRouteImport,
} as any)
const MetasRoute = MetasRouteImport.update({
  id: '/metas',
  path: '/metas',
  getParentRoute: () => rootRouteImport,
} as any)
const ManualRoute = ManualRouteImport.update({
  id: '/manual',
  path: '/manual',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GuardadoRoute = GuardadoRouteImport.update({
  id: '/guardado',
  path: '/guardado',
  getParentRoute: () => rootRouteImport,
} as any)
const GastosRoute = GastosRouteImport.update({
  id: '/gastos',
  path: '/gastos',
  getParentRoute: () => rootRouteImport,
} as any)
const ContasAPagarRoute = ContasAPagarRouteImport.update({
  id: '/contas-a-pagar',
  path: '/contas-a-pagar',
  getParentRoute: () => rootRouteImport,
} as any)
const ContaRoute = ContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmarRoute = ConfirmarRouteImport.update({
  id: '/confirmar',
  path: '/confirmar',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriasRoute = CategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => rootRouteImport,
} as any)
const CartoesRoute = CartoesRouteImport.update({
  id: '/cartoes',
  path: '/cartoes',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const AdicionarRoute = AdicionarRouteImport.update({
  id: '/adicionar',
  path: '/adicionar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOcrGastoRoute = ApiOcrGastoRouteImport.update({
  id: '/api/ocr-gasto',
  path: '/api/ocr-gasto',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImportFaturaPdfRoute = ApiImportFaturaPdfRouteImport.update({
  id: '/api/import-fatura-pdf',
  path: '/api/import-fatura-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImportFaturaImagemRoute = ApiImportFaturaImagemRouteImport.update({
  id: '/api/import-fatura-imagem',
  path: '/api/import-fatura-imagem',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImportExtratoRoute = ApiImportExtratoRouteImport.update({
  id: '/api/import-extrato',
  path: '/api/import-extrato',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImportContaPdfRoute = ApiImportContaPdfRouteImport.update({
  id: '/api/import-conta-pdf',
  path: '/api/import-conta-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImportContaRoute = ApiImportContaRouteImport.update({
  id: '/api/import-conta',
  path: '/api/import-conta',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/adicionar': typeof AdicionarRoute
  '/cadastro': typeof CadastroRoute
  '/cartoes': typeof CartoesRoute
  '/categorias': typeof CategoriasRoute
  '/confirmar': typeof ConfirmarRoute
  '/conta': typeof ContaRoute
  '/contas-a-pagar': typeof ContasAPagarRoute
  '/gastos': typeof GastosRoute
  '/guardado': typeof GuardadoRoute
  '/login': typeof LoginRoute
  '/manual': typeof ManualRoute
  '/metas': typeof MetasRoute
  '/meu-plano': typeof MeuPlanoRoute
  '/orcamento': typeof OrcamentoRoute
  '/perfil': typeof PerfilRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/relatorios': typeof RelatoriosRoute
  '/renda': typeof RendaRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resumo': typeof ResumoRoute
  '/api/import-conta': typeof ApiImportContaRoute
  '/api/import-conta-pdf': typeof ApiImportContaPdfRoute
  '/api/import-extrato': typeof ApiImportExtratoRoute
  '/api/import-fatura-imagem': typeof ApiImportFaturaImagemRoute
  '/api/import-fatura-pdf': typeof ApiImportFaturaPdfRoute
  '/api/ocr-gasto': typeof ApiOcrGastoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/adicionar': typeof AdicionarRoute
  '/cadastro': typeof CadastroRoute
  '/cartoes': typeof CartoesRoute
  '/categorias': typeof CategoriasRoute
  '/confirmar': typeof ConfirmarRoute
  '/conta': typeof ContaRoute
  '/contas-a-pagar': typeof ContasAPagarRoute
  '/gastos': typeof GastosRoute
  '/guardado': typeof GuardadoRoute
  '/login': typeof LoginRoute
  '/manual': typeof ManualRoute
  '/metas': typeof MetasRoute
  '/meu-plano': typeof MeuPlanoRoute
  '/orcamento': typeof OrcamentoRoute
  '/perfil': typeof PerfilRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/relatorios': typeof RelatoriosRoute
  '/renda': typeof RendaRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resumo': typeof ResumoRoute
  '/api/import-conta': typeof ApiImportContaRoute
  '/api/import-conta-pdf': typeof ApiImportContaPdfRoute
  '/api/import-extrato': typeof ApiImportExtratoRoute
  '/api/import-fatura-imagem': typeof ApiImportFaturaImagemRoute
  '/api/import-fatura-pdf': typeof ApiImportFaturaPdfRoute
  '/api/ocr-gasto': typeof ApiOcrGastoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/adicionar': typeof AdicionarRoute
  '/cadastro': typeof CadastroRoute
  '/cartoes': typeof CartoesRoute
  '/categorias': typeof CategoriasRoute
  '/confirmar': typeof ConfirmarRoute
  '/conta': typeof ContaRoute
  '/contas-a-pagar': typeof ContasAPagarRoute
  '/gastos': typeof GastosRoute
  '/guardado': typeof GuardadoRoute
  '/login': typeof LoginRoute
  '/manual': typeof ManualRoute
  '/metas': typeof MetasRoute
  '/meu-plano': typeof MeuPlanoRoute
  '/orcamento': typeof OrcamentoRoute
  '/perfil': typeof PerfilRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/relatorios': typeof RelatoriosRoute
  '/renda': typeof RendaRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resumo': typeof ResumoRoute
  '/api/import-conta': typeof ApiImportContaRoute
  '/api/import-conta-pdf': typeof ApiImportContaPdfRoute
  '/api/import-extrato': typeof ApiImportExtratoRoute
  '/api/import-fatura-imagem': typeof ApiImportFaturaImagemRoute
  '/api/import-fatura-pdf': typeof ApiImportFaturaPdfRoute
  '/api/ocr-gasto': typeof ApiOcrGastoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/adicionar'
    | '/cadastro'
    | '/cartoes'
    | '/categorias'
    | '/confirmar'
    | '/conta'
    | '/contas-a-pagar'
    | '/gastos'
    | '/guardado'
    | '/login'
    | '/manual'
    | '/metas'
    | '/meu-plano'
    | '/orcamento'
    | '/perfil'
    | '/recuperar-senha'
    | '/relatorios'
    | '/renda'
    | '/reset-password'
    | '/resumo'
    | '/api/import-conta'
    | '/api/import-conta-pdf'
    | '/api/import-extrato'
    | '/api/import-fatura-imagem'
    | '/api/import-fatura-pdf'
    | '/api/ocr-gasto'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/adicionar'
    | '/cadastro'
    | '/cartoes'
    | '/categorias'
    | '/confirmar'
    | '/conta'
    | '/contas-a-pagar'
    | '/gastos'
    | '/guardado'
    | '/login'
    | '/manual'
    | '/metas'
    | '/meu-plano'
    | '/orcamento'
    | '/perfil'
    | '/recuperar-senha'
    | '/relatorios'
    | '/renda'
    | '/reset-password'
    | '/resumo'
    | '/api/import-conta'
    | '/api/import-conta-pdf'
    | '/api/import-extrato'
    | '/api/import-fatura-imagem'
    | '/api/import-fatura-pdf'
    | '/api/ocr-gasto'
  id:
    | '__root__'
    | '/'
    | '/adicionar'
    | '/cadastro'
    | '/cartoes'
    | '/categorias'
    | '/confirmar'
    | '/conta'
    | '/contas-a-pagar'
    | '/gastos'
    | '/guardado'
    | '/login'
    | '/manual'
    | '/metas'
    | '/meu-plano'
    | '/orcamento'
    | '/perfil'
    | '/recuperar-senha'
    | '/relatorios'
    | '/renda'
    | '/reset-password'
    | '/resumo'
    | '/api/import-conta'
    | '/api/import-conta-pdf'
    | '/api/import-extrato'
    | '/api/import-fatura-imagem'
    | '/api/import-fatura-pdf'
    | '/api/ocr-gasto'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdicionarRoute: typeof AdicionarRoute
  CadastroRoute: typeof CadastroRoute
  CartoesRoute: typeof CartoesRoute
  CategoriasRoute: typeof CategoriasRoute
  ConfirmarRoute: typeof ConfirmarRoute
  ContaRoute: typeof ContaRoute
  ContasAPagarRoute: typeof ContasAPagarRoute
  GastosRoute: typeof GastosRoute
  GuardadoRoute: typeof GuardadoRoute
  LoginRoute: typeof LoginRoute
  ManualRoute: typeof ManualRoute
  MetasRoute: typeof MetasRoute
  MeuPlanoRoute: typeof MeuPlanoRoute
  OrcamentoRoute: typeof OrcamentoRoute
  PerfilRoute: typeof PerfilRoute
  RecuperarSenhaRoute: typeof RecuperarSenhaRoute
  RelatoriosRoute: typeof RelatoriosRoute
  RendaRoute: typeof RendaRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ResumoRoute: typeof ResumoRoute
  ApiImportContaRoute: typeof ApiImportContaRoute
  ApiImportContaPdfRoute: typeof ApiImportContaPdfRoute
  ApiImportExtratoRoute: typeof ApiImportExtratoRoute
  ApiImportFaturaImagemRoute: typeof ApiImportFaturaImagemRoute
  ApiImportFaturaPdfRoute: typeof ApiImportFaturaPdfRoute
  ApiOcrGastoRoute: typeof ApiOcrGastoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/resumo': {
      id: '/resumo'
      path: '/resumo'
      fullPath: '/resumo'
      preLoaderRoute: typeof ResumoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/renda': {
      id: '/renda'
      path: '/renda'
      fullPath: '/renda'
      preLoaderRoute: typeof RendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar-senha': {
      id: '/recuperar-senha'
      path: '/recuperar-senha'
      fullPath: '/recuperar-senha'
      preLoaderRoute: typeof RecuperarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orcamento': {
      id: '/orcamento'
      path: '/orcamento'
      fullPath: '/orcamento'
      preLoaderRoute: typeof OrcamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meu-plano': {
      id: '/meu-plano'
      path: '/meu-plano'
      fullPath: '/meu-plano'
      preLoaderRoute: typeof MeuPlanoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metas': {
      id: '/metas'
      path: '/metas'
      fullPath: '/metas'
      preLoaderRoute: typeof MetasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manual': {
      id: '/manual'
      path: '/manual'
      fullPath: '/manual'
      preLoaderRoute: typeof ManualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guardado': {
      id: '/guardado'
      path: '/guardado'
      fullPath: '/guardado'
      preLoaderRoute: typeof GuardadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gastos': {
      id: '/gastos'
      path: '/gastos'
      fullPath: '/gastos'
      preLoaderRoute: typeof GastosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contas-a-pagar': {
      id: '/contas-a-pagar'
      path: '/contas-a-pagar'
      fullPath: '/contas-a-pagar'
      preLoaderRoute: typeof ContasAPagarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conta': {
      id: '/conta'
      path: '/conta'
      fullPath: '/conta'
      preLoaderRoute: typeof ContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirmar': {
      id: '/confirmar'
      path: '/confirmar'
      fullPath: '/confirmar'
      preLoaderRoute: typeof ConfirmarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categorias': {
      id: '/categorias'
      path: '/categorias'
      fullPath: '/categorias'
      preLoaderRoute: typeof CategoriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cartoes': {
      id: '/cartoes'
      path: '/cartoes'
      fullPath: '/cartoes'
      preLoaderRoute: typeof CartoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adicionar': {
      id: '/adicionar'
      path: '/adicionar'
      fullPath: '/adicionar'
      preLoaderRoute: typeof AdicionarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ocr-gasto': {
      id: '/api/ocr-gasto'
      path: '/api/ocr-gasto'
      fullPath: '/api/ocr-gasto'
      preLoaderRoute: typeof ApiOcrGastoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/import-fatura-pdf': {
      id: '/api/import-fatura-pdf'
      path: '/api/import-fatura-pdf'
      fullPath: '/api/import-fatura-pdf'
      preLoaderRoute: typeof ApiImportFaturaPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/import-fatura-imagem': {
      id: '/api/import-fatura-imagem'
      path: '/api/import-fatura-imagem'
      fullPath: '/api/import-fatura-imagem'
      preLoaderRoute: typeof ApiImportFaturaImagemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/import-extrato': {
      id: '/api/import-extrato'
      path: '/api/import-extrato'
      fullPath: '/api/import-extrato'
      preLoaderRoute: typeof ApiImportExtratoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/import-conta-pdf': {
      id: '/api/import-conta-pdf'
      path: '/api/import-conta-pdf'
      fullPath: '/api/import-conta-pdf'
      preLoaderRoute: typeof ApiImportContaPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/import-conta': {
      id: '/api/import-conta'
      path: '/api/import-conta'
      fullPath: '/api/import-conta'
      preLoaderRoute: typeof ApiImportContaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdicionarRoute: AdicionarRoute,
  CadastroRoute: CadastroRoute,
  CartoesRoute: CartoesRoute,
  CategoriasRoute: CategoriasRoute,
  ConfirmarRoute: ConfirmarRoute,
  ContaRoute: ContaRoute,
  ContasAPagarRoute: ContasAPagarRoute,
  GastosRoute: GastosRoute,
  GuardadoRoute: GuardadoRoute,
  LoginRoute: LoginRoute,
  ManualRoute: ManualRoute,
  MetasRoute: MetasRoute,
  MeuPlanoRoute: MeuPlanoRoute,
  OrcamentoRoute: OrcamentoRoute,
  PerfilRoute: PerfilRoute,
  RecuperarSenhaRoute: RecuperarSenhaRoute,
  RelatoriosRoute: RelatoriosRoute,
  RendaRoute: RendaRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ResumoRoute: ResumoRoute,
  ApiImportContaRoute: ApiImportContaRoute,
  ApiImportContaPdfRoute: ApiImportContaPdfRoute,
  ApiImportExtratoRoute: ApiImportExtratoRoute,
  ApiImportFaturaImagemRoute: ApiImportFaturaImagemRoute,
  ApiImportFaturaPdfRoute: ApiImportFaturaPdfRoute,
  ApiOcrGastoRoute: ApiOcrGastoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
