/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ManualRouteImport } from './routes/manual'
import { Route as AdicionarRouteImport } from './routes/adicionar'
import { Route as IndexRouteImport } from './routes/index'

const ManualRoute = ManualRouteImport.update({
  id: '/manual',
  path: '/manual',
  getParentRoute: () => rootRouteImport,
} as any)
const AdicionarRoute = AdicionarRouteImport.update({
  id: '/adicionar',
  path: '/adicionar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/adicionar': typeof AdicionarRoute
  '/manual': typeof ManualRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/adicionar': typeof AdicionarRoute
  '/manual': typeof ManualRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/adicionar': typeof AdicionarRoute
  '/manual': typeof ManualRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/adicionar' | '/manual'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/adicionar' | '/manual'
  id: '__root__' | '/' | '/adicionar' | '/manual'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdicionarRoute: typeof AdicionarRoute
  ManualRoute: typeof ManualRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/manual': {
      id: '/manual'
      path: '/manual'
      fullPath: '/manual'
      preLoaderRoute: typeof ManualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adicionar': {
      id: '/adicionar'
      path: '/adicionar'
      fullPath: '/adicionar'
      preLoaderRoute: typeof AdicionarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdicionarRoute: AdicionarRoute,
  ManualRoute: ManualRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
